### ISSUE TITLE
let's do something awesome

### ISSUE THREAD

**Issue by jovo** [jwittenbach/brainreading#1]
@jwittenbach @bcoke

**Comment by bcocanougher** [comment]
Well, would you look at that? Would you just look at it?

We should add the code that Jason was playing around with during the meeting so that we can load it in and look at it.

**Comment by jwittenbach** [comment]
I'm all for the awesome =)

@bcoke I will definitely upload the code for loading the data. However it won't be too useful until we get the data somewhere that everyone can view it. There was a conversation with @jovo and @freeman-lab where we thought that putting the data on S3 might be the best way to go and then everyone can load it from there. However, we should run this past Marta and Nadine, since it would technically be publicly accessible.

**Comment by jovo** [comment]
yup, S3 is fine, so is putting it on my server.

On Thu, Nov 5, 2015 at 11:31 AM, Jason Wittenbach notifications@github.com
wrote:

> I'm all for the awesome =)
> 
> @bcoke https://github.com/bcoke I will definitely upload the code for
> loading the data. However it won't be too useful until we get the data
> somewhere that everyone can view it. There was a conversation with @jovo
> https://github.com/jovo and @freeman-lab
> https://github.com/freeman-lab where we thought that putting the data
> on S3 might be the best way to go and then everyone can load it from there.
> However, we should run this past Marta and Nadine, since it would
> technically be publicly accessible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jwittenbach/brainreading/issues/1#issuecomment-154113519
> .

## 

the glass is all full:  half water, half air.
neurodata.io
